### ISSUE TITLE
Music doesn't stop when window focus is lost

### ISSUE THREAD

**Issue by BrokeStudio** [gradualgames/ggvm#2]
When GGvm is windowed, if you click outside of the window, the menu opens correctly to "pause" the program, but music is still going on.
When clicking in the window after that, the menu goes off, but the music stops briefly before resuming.

I guess that it should behave like when you open the main menu by pressing Escape.

**Comment by gradualgames** [comment]
Should be resolved now as of d088e35e5fc9b35c4d32c76b8352a2705ad9ab05
